title: Website Anita Posch
default_lang: en
author:
  name: 'Anita Posch'
  email: hello@poshmedia.eu
taxonomies:
  - category
  - tags
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes:
  '/category/(.+)': '/category'
blog:
  route: /blog
