title: Anita
default_lang: en
author:
  name: 'Anita'
taxonomies:
  - category
  - tags
metadata:
  description: "Anita focuses on how Bitcoin and decentralized technology provide financial freedom, privacy and human rights for those who need it most. She is the founder of Bitcoin for Fairness and due to her long work on the ground an expert on Bitcoin adoption in Africa."
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes:
  '/category/(.+)': '/category'
  '/feed': '/blog'
  '/feed.rss': '/blog.rss'
blog:
  route: /blog
