title: Anita Posch | Change Maker & Freedom Tech Advocate
default_lang: en
author:
  name: 'Anita Posch'
taxonomies:
  - category
  - tags
metadata:
  description: "Anita Posch focuses on how Bitcoin and decentralized technology provide financial freedom, privacy and human rights protection for those who need it most. She is an author, founder of Bitcoin for Fairness and expert on Bitcoin adoption in Africa."
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes:
  '/category/(.+)': '/category'
  '/feed': '/blog'
  '/feed.rss': '/blog.rss'
blog:
  route: /blog
