enabled: true
facebook: null
twitter: null
instagram: null
company_name: 'Anita'
phone: null
email: null
location: null
logo:
  user/themes/tail-land/images/logo/anita-logo.png:
    name: anita-logo.png
    full_path: anita-logo.png
    type: image/png
    size: 35061
    path: user/themes/tail-land/images/logo/anita-logo.png
